name: Linter

on:
  # allows manual trigger
  workflow_dispatch:
  # allows other workflows to call this workflow
  workflow_call:
  pull_request:

jobs:
  python-lint:
    runs-on: ubuntu-latest
    name: CI workflow
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Check if requirements.txt exists
        id: check-file
        run: |
          if [ -f requirements.txt ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create empty requirements.txt if not found
        if: steps.check-file.outputs.exists == 'false'
        run: echo "" > requirements.txt

      - name: Linter
        id: linter
        uses: tibtiq/python-lint-annotate@625e1960d84b63c2b2d8738ba9283e7a8ba1b864
        with:
          python-root-list: "src/"
          extra-pylint-options: "--disable=W1202,W1203,C0116"
          extra-pycodestyle-options: "--config=.pycodestyle"
          use-vulture: false
          use-black: false

      - name: Fail workflow if linter has errors
        run: |
          # Define the phrases to search for
          phrases=("Pylint error" "pycodestyle error" "Flake8 error" "mypy error" "isort error" "pycodestyle error")

          # Read the output log
          echo "Reusable workflow result: ${{ steps.linter.outputs.command_output }}"

          output=$(${{ steps.linter.outputs.command_output }})

          # Check each phrase
          for phrase in "${phrases[@]}"; do
            if echo "$output" | grep -q "$phrase"; then
              echo "Found prohibited phrase: $phrase"
              exit 1
            fi
          done

          echo "No prohibited phrases found."