env:
  DESTINATION_USERNAME: dennisvtang
  DESTINATION_REPOSITORY: youtube-api-data-transfer
  DESTINATION_BRANCH: add-or-update-python-linters
  COMMIT_EMAIL: dennisvtang@gmail.com
  SOURCE_FILES: |
    .github/workflows/ci.yml
    configs/

on:
  # allows manual trigger
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Push github action and configs
      uses: dennisvtang/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.REPO_TOKEN }}
      with:
        user_name: ${{ env.DESTINATION_USERNAME }}
        user_email: ${{ env.COMMIT_EMAIL }}
        destination_repo: ${{ env.DESTINATION_USERNAME }}/${{ env.DESTINATION_REPOSITORY }}
        destination_branch_create: ${{ env.DESTINATION_BRANCH }}
        use_rsync: true
        push_with_force: true
        source_files: ${{ env.SOURCE_FILES }}

    - name: Get last commit SHA from python-linters
      id: python-linters-commit-sha
      run: |
        echo "commit_sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"

    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.REPO_TOKEN }}
        repository: ${{ env.DESTINATION_USERNAME }}/${{ env.DESTINATION_REPOSITORY }}
        ref: ${{ env.DESTINATION_BRANCH }}

    - name: Create pull request
      id: pull-request
      run: |
        gh pr create \
        --base 'main' \
        --head ${{ env.DESTINATION_BRANCH }} \
        --title 'Add or update python linters' \
        --body 'Update from ${{ github.repository }}@${{steps.python-linters-commit-sha.outputs.commit_sha}}' \
        --label 'github action' \
        --label 'bot' \
        --assignee '@me'
      env:
        GH_TOKEN: ${{ secrets.REPO_TOKEN }}

    - name: Get pull request success
      run: |
        num_pull_requests=$(gh pr list --json title --jq length)
        if ((num_pull_requests > 0)); then
          echo "success=true" >> $GITHUB_ENV
        else
          echo "success=false" >> $GITHUB_ENV
        fi

      env:
        GH_TOKEN: ${{ secrets.REPO_TOKEN }}

    - name: Get pull request info
      id: pull-request-info
      run: |
        pull_request_url=$(gh pr view ${{ env.DESTINATION_BRANCH }} --json url --jq .url)
        echo "pull-request-url=$pull_request_url" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ secrets.REPO_TOKEN }}

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      if: steps.pull-request-info.outputs.success == 'true'
      with:
        # Required mail server address if not connection_url:
        server_address: smtp.gmail.com
        # Server port, https://support.google.com/a/answer/176600?hl=en#:~:text=relay.gmail.com.-,Configuration,-options%20include%3A
        server_port: 465
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # mail server username:
        username: ${{secrets.GOOGLE_EMAIL_USERNAME}}
        # mail server password:
        password: ${{secrets.GOOGLE_EMAIL_PASSWORD}}
        # Required mail subject:
        subject: "[${{ env.DESTINATION_USERNAME }}/${{ env.DESTINATION_REPOSITORY }}] Add or update python linters"
        # Required recipients' addresses:
        to: ${{secrets.GOOGLE_EMAIL_USERNAME}}
        # Required sender full name (address can be skipped):
        from: '${{ env.DESTINATION_REPOSITORY }}@github.com'
        # Optional plain body:
        html_body: |
          [${{ env.DESTINATION_REPOSITORY }} pull request](${{ steps.pull-request-info.outputs.pull-request-url }})
        convert_markdown: true