env:
  DESTINATION_USERNAME: 'dennisvtang'
  DESTINATION_REPOSITORY: 'youtube-api-data-transfer'
  COMMIT_EMAIL: 'dennisvtang@gmail.com'

on:
  # allows manual trigger
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Push github action and configs
      uses: dennisvtang/copy_file_to_another_repo_action_push_force@HEAD

      env:
        API_TOKEN_GITHUB: ${{ secrets.REPO_TOKEN }}
      with:
        user_name: ${{ env.DESTINATION_USERNAME }}
        user_email: ${{ env.COMMIT_EMAIL }}
        source_files: |
          .github/workflows/ci.yml
          configs/
        destination_repo: ${{ env.DESTINATION_USERNAME }}/${{ env.DESTINATION_REPOSITORY }}
        destination_branch_create: 'add-or-update-python-linters'
        use_rsync: true