env:
  DESTINATION_USERNAME: 'dennisvtang'
  DESTINATION_REPOSITORY: 'youtube-api-data-transfer'
  COMMIT_EMAIL: 'dennisvtang@gmail.com'
  SOURCE_FILES: |
    .github/workflows/ci.yml
    configs/

on:
  # allows manual trigger
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Push github action and configs
      uses: dennisvtang/copy_file_to_another_repo_action@latest
      env:
        API_TOKEN_GITHUB: ${{ secrets.REPO_TOKEN }}
      with:
        user_name: ${{ env.DESTINATION_USERNAME }}
        user_email: ${{ env.COMMIT_EMAIL }}
        destination_repo: ${{ env.DESTINATION_USERNAME }}/${{ env.DESTINATION_REPOSITORY }}
        destination_branch_create: 'add-or-update-python-linters'
        use_rsync: true
        push_with_force: true
        source_files: ${{ env.SOURCE_FILES }}