name: Formatter and Linter

on:
  # allows other workflows to call this workflow
  workflow_call:
  push:

jobs:
  lock_file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv lock --locked

  tests:
    runs-on: ubuntu-latest
    needs: [lock_file]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5

      - name: Run Unit Tests
        run: uv run pytest -v --durations=0 --cov --cov-report=xml

      - name: Run Integration Tests (Dependabot PRs only)
        if: github.actor == 'dependabot[bot]'
        run: pytest --run-integration -m integration